version: "3.9"

services:
  apache:
    hostname: ${APACHE_NAME}
    container_name: ${APACHE_NAME}
    image: mikel00per/${APACHE_NAME}
    build:
      context: ${APACHE_CONTEXT}
      args:
        APACHE_VERSION: "${APACHE_VERSION}"
        APACHE_CONFIG_TARGET: "${APACHE_CONFIG_TARGET}"
        APACHE_CONFIG_SOURCE: "${APACHE_CONFIG_SOURCE}"
        APACHE_CONFIG_INCLUDE: "${APACHE_CONFIG_INCLUDE}"
    ports:
      - ${APACHE_HTTP_PORT}:${APACHE_HTTP_PORT}
      - ${APACHE_HTTPS_PORT}:${APACHE_HTTPS_PORT}

  mysql:
    hostname: ${MYSQL_NAME}
    container_name: ${MYSQL_NAME}
    image: mikel00per/${MYSQL_NAME}
    build:
      context: ${MYSQL_CONTEXT}
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_CONFIG_SOURCE: ${MYSQL_CONFIG_SOURCE}
        MYSQL_CONFIG_TARGET: ${MYSQL_CONFIG_TARGET}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  nginx:
    hostname: ${NGINX_NAME}
    container_name: ${NGINX_NAME}
    image: mikel00per/${NGINX_NAME}
    build:
      context: ${NGINX_CONTEXT}
      args:
        NGINX_VERSION: ${NGINX_VERSION}
        NGINX_CONFIG_SOURCE: ${NGINX_CONFIG_SOURCE}
        NGINX_CONFIG_TARGET: ${NGINX_CONFIG_TARGET}
    ports:
      - ${NINGX_HTTP_PORT}:${NINGX_HTTP_PORT}
      - ${NINGX_HTTPS_PORT}:${NINGX_HTTPS_PORT}

  php:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    image: mikel00per/${PHP_NAME}
    build:
      context: ${PHP_CONTEXT}
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
    ports:
      - ${PHP_PORT}:${PHP_PORT}