version: "3.9"

services:
  mysql-development:
    hostname: ${MYSQL_NAME}
    container_name: ${MYSQL_NAME}
    image: mikel00per/${MYSQL_NAME}
    env_file:
      - development/.env
    build:
      context: ${MYSQL_CONTEXT}
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_CONFIG_SOURCE: ${MYSQL_CONFIG_SOURCE}
        MYSQL_CONFIG_TARGET: ${MYSQL_CONFIG_TARGET}
        MYSQL_HEALTHCHECK_SOURCE: ${MYSQL_HEALTHCHECK_SOURCE}
        MYSQL_HEALTHCHECK_TARGET: ${MYSQL_HEALTHCHECK_TARGET}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  mysql-production:
    hostname: ${MYSQL_NAME}
    container_name: ${MYSQL_NAME}
    image: mikel00per/${MYSQL_NAME}
    env_file:
      - production/.env
    build:
      context: ${MYSQL_CONTEXT}
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_CONFIG_SOURCE: ${MYSQL_CONFIG_SOURCE}
        MYSQL_CONFIG_TARGET: ${MYSQL_CONFIG_TARGET}
        MYSQL_HEALTHCHECK_SOURCE: ${MYSQL_HEALTHCHECK_SOURCE}
        MYSQL_HEALTHCHECK_TARGET: ${MYSQL_HEALTHCHECK_TARGET}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}