version: "3.9"

services:
  mysql-development:
    hostname: ${MYSQL_NAME}
    container_name: ${MYSQL_NAME}
    image: mikel00per/${MYSQL_NAME}
    env_file:
      - development/.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    build:
      context: ${MYSQL_CONTEXT}
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_CONFIG_SOURCE: ${MYSQL_CONFIG_SOURCE}
        MYSQL_CONFIG_TARGET: ${MYSQL_CONFIG_TARGET}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}

  mysql-production:
    hostname: ${MYSQL_NAME}
    container_name: ${MYSQL_NAME}
    image: mikel00per/${MYSQL_NAME}
    env_file:
      - production/.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    build:
      context: ${MYSQL_CONTEXT}
      args:
        MYSQL_VERSION: ${MYSQL_VERSION}
        MYSQL_CONFIG_SOURCE: ${MYSQL_CONFIG_SOURCE}
        MYSQL_CONFIG_TARGET: ${MYSQL_CONFIG_TARGET}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}