version: "3.9"

services:

  php-development:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    image: mikel00per/${PHP_NAME}
    build:
      context: ${PHP_CONTEXT}
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_FPM_CONFIG_SOURCE: ${PHP_FPM_CONFIG_SOURCE}
        PHP_FPM_CONFIG_TARGET: ${PHP_FPM_CONFIG_TARGET}
        PHP_APCU_CONFIG_SOURCE: ${PHP_APCU_CONFIG_SOURCE}
        PHP_APCU_CONFIG_TARGET: ${PHP_APCU_CONFIG_TARGET}
        PHP_OPCACHE_CONFIG_SOURCE: ${PHP_OPCACHE_CONFIG_SOURCE}
        PHP_OPCACHE_CONFIG_TARGET: ${PHP_OPCACHE_CONFIG_TARGET}
        PHP_XDEBUG_CONFIG_SOURCE: ${PHP_XDEBUG_CONFIG_SOURCE}
        PHP_XDEBUG_CONFIG_TARGET: ${PHP_XDEBUG_CONFIG_TARGET}
        PHP_CODE_TARGET: ${PHP_CODE_TARGET}
        PHP_ENTRYPOINT_SOURCE: ${PHP_ENTRYPOINT_SOURCE}
        PHP_ENTRYPOINT_TARGET: ${PHP_ENTRYPOINT_TARGET}
        PHP_HEALTHCHECK_SOURCE: ${PHP_HEALTHCHECK_SOURCE}
        PHP_HEALTHCHECK_TARGET: ${PHP_HEALTHCHECK_TARGET}
        SUPERVISORD_CONFIG_SOURCE: ${SUPERVISORD_CONFIG_SOURCE}
        SUPERVISORD_CONFIG_TARGET: ${SUPERVISORD_CONFIG_TARGET}
        PHP_PORT: ${PHP_PORT}
    ports:
      - ${PHP_PORT}:${PHP_PORT}
    networks:
      - default
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
      test: ['CMD', 'docker-healthcheck']

  php-production:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    image: mikel00per/${PHP_NAME}
    build:
      context: ${PHP_CONTEXT}
      args:
        UID: ${UID}
        GID: ${GID}
        UNAME: ${UNAME}
        GNAME: ${GNAME}
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_FPM_CONFIG_SOURCE: ${PHP_FPM_CONFIG_SOURCE}
        PHP_FPM_CONFIG_TARGET: ${PHP_FPM_CONFIG_TARGET}
        PHP_APCU_CONFIG_SOURCE: ${PHP_APCU_CONFIG_SOURCE}
        PHP_APCU_CONFIG_TARGET: ${PHP_APCU_CONFIG_TARGET}
        PHP_OPCACHE_CONFIG_SOURCE: ${PHP_OPCACHE_CONFIG_SOURCE}
        PHP_OPCACHE_CONFIG_TARGET: ${PHP_OPCACHE_CONFIG_TARGET}
        PHP_CODE_TARGET: ${PHP_CODE_TARGET}
        PHP_ENTRYPOINT_SOURCE: ${PHP_ENTRYPOINT_SOURCE}
        PHP_ENTRYPOINT_TARGET: ${PHP_ENTRYPOINT_TARGET}
        PHP_HEALTHCHECK_SOURCE: ${PHP_HEALTHCHECK_SOURCE}
        PHP_HEALTHCHECK_TARGET: ${PHP_HEALTHCHECK_TARGET}
        SUPERVISORD_CONFIG_SOURCE: ${SUPERVISORD_CONFIG_SOURCE}
        SUPERVISORD_CONFIG_TARGET: ${SUPERVISORD_CONFIG_TARGET}
        PHP_PORT: ${PHP_PORT}
    ports:
      - ${PHP_PORT}:${PHP_PORT}
    networks:
      - default
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

networks:
  default:
    name: backend
    driver: bridge
