version: "3.9"

services:

  php-development:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    image: mikel00per/${PHP_NAME}
    build:
      context: ${PHP_CONTEXT}
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_CODE_TARGET: ${PHP_CODE_TARGET}
        PHP_ENTRYPOINT_SOURCE: ${PHP_ENTRYPOINT_SOURCE}
        PHP_ENTRYPOINT_TARGET: ${PHP_ENTRYPOINT_TARGET}
    ports:
      - ${PHP_PORT}:${PHP_PORT}

  php-production:
    hostname: ${PHP_NAME}
    container_name: ${PHP_NAME}
    image: mikel00per/${PHP_NAME}
    build:
      context: ${PHP_CONTEXT}
      args:
        PHP_VERSION: ${PHP_VERSION}
        PHP_CONFIG_SOURCE: ${PHP_CONFIG_SOURCE}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_CONFIG_TARGET: ${PHP_CONFIG_TARGET}
        PHP_CODE_TARGET: ${PHP_CODE_TARGET}
        PHP_ENTRYPOINT_SOURCE: ${PHP_ENTRYPOINT_SOURCE}
        PHP_ENTRYPOINT_TARGET: ${PHP_ENTRYPOINT_TARGET}
    ports:
      - ${PHP_PORT}:${PHP_PORT}
