name: Deploy Containers

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build-php-development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image php
        run: ./configure.sh

      - name: Build image php
        run: make build-php-development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image php
        run: make push-php-development

  build-php-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image php
        run: ./configure.sh

      - name: Build image php
        run: make build-php-production

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image php
        run: make push-php-production

  build-nginx-development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image nginx
        run: ./configure.sh

      - name: Build image nginx
        run: make build-nginx-development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image nginx
        run: make push-nginx-development

  build-nginx-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image nginx
        run: ./configure.sh

      - name: Build image nginx
        run: make build-nginx-production

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image nginx
        run: make push-nginx-production
