name: Deploy MySQL Containers

on:
  push:
    branches: [ dev ]
    paths:
      - 'mysql/**'

jobs:
  deploy-mysql-development:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image mysql
        run: ./configure.sh

      - name: Build image mysql
        run: make build-mysql-development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image mysql
        run: make push-mysql-development

  deploy-mysql-production:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image mysql
        run: ./configure.sh

      - name: Build image mysql
        run: make build-mysql-production

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image mysql
        run: make push-mysql-production
