name: Deploy PHP Containers

on:
  push:
    branches: [ dev ]
    paths:
      - 'php/**'

jobs:
  php-development-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image php
        run: ./configure.sh

      - name: Build image php
        run: make build-php-development

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image php
        run: make push-php-development

  php-production-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Config environment to build image php
        run: ./configure.sh

      - name: Build image php
        run: make build-php-production

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push image php
        run: make push-php-production
